# Site settings
title: ViVi CAO's Blog
SEOTitle: 草脏脏的博客 | ViVi Blog
header-img: img/home-bg.jpeg
email: cdlie2m122@163.com
description: "做一个有想法的搬运工 | 草婷，Android engineer，Programmer | 这里是 @草脏脏 的个人博客，与你分享我的真实世界。"
keyword: "草脏脏, vv草脏脏, ViVi, cwgoover, applecao520, @applecao520, 草脏脏的博客, ViVi Blog, 博客, 个人网站, Android, Java, Python, Linux, Art"
url: "https://cwgoover.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# TODO: need to check real account
# SNS settings
RSS: false
#weibo_username:     草脏脏
zhihu_username:     草脏脏
# stack_username:  [check]
github_username:    草脏脏
#twitter_username:  applecao520
#facebook_username:  applecao520
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "page:num"

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# TODO: need to register???
# Duoshuo settings
duoshuo_username: viviblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# TODO: need to change
# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: cwgoover.ho



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Were not we having tears in our eyes through past of the years?"
sidebar-avatar: /img/avatar-vivi.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# TODO: need to change
# Friends
friends: [
    {
        title: "Android Developer",
        href: "http://android.developer.com"
    },{
        title: "StackOverflow",
        href: "http://www.stackoverflow.com"
    }
]
